Contributor.md

Hey, I've made the challenge number one! 😄 Thanks for these challenges, they're very good to learn how does git works, and to use this knowledge in other project! I'm also looking foward to the other challenges :)

Challenge #1 Ana Vitória

---

About-Me/avet.md

Next step 😸 ! Thanks again for the challenges

Challenge #2

---

About-Me/jm.md
Contributor.md
Scripts/joseph.py

Issue #13 
Sorta went overboard and did up to Challenges 3.
I figured it wasn't feasible to work on one branch and only submit a PR when the previous one gets accepted.
```Shell
$:  cd Scripts
$:  python joseph.py
```
Does the neat trick of saying hi to everyone in the `Scripts/` folder.
If you're going to merge this, please add label of `hacktoberfest-accepted`

Added to Contributor.md, About-Me and Scripts

---

README Portuguese.md

Hey, I translated the README file to Portuguese so more people with less English experience could also participate, is that ok for you?

Translated the README.md to portuguese

---

Contributor.md

Thank you for the opportunity to contribute!

Added name to contributor list

---

Scripts/fibonacci.cpp

C++ program to find a fibonacci number in Nth position from generating fibonacci number from f1 to f2

Add fibonacci.cpp

---

Scripts/AdditonOfDigitsOfAGivenNumber.py

Added AdditonOfDigitsOfAGivenNumber.py

---

Scripts/CountingOccurrenceOfEachWord.py

Added CountingOccurrenceOfEachWord.py

---

Scripts/DoublyLinkedList.py

Added DoublyLinkedList.py

---

Scripts/KaperkerNumbers.py

Added KaperkerNumbers.py

---

Scripts/RomanToInteger.py

Added RomanToInteger.py

---

Scripts/Leibniz'sFormulaForCalculatingPi.py

Added Leibniz'sFormulaForCalculatingPi.py

---

Contributor.md

Added my details at the end of the file as asked. Thanks!
[Link to previous PR](https://github.com/jinwoov/hacktoberfest/pull/53)

Updated contributors.md file

---

About-Me/at.md

Updated About-Me

---

Scripts/uniqueWithXOR.cpp

Hello!
I have added a program to find the unique element from a array where all others occur twice using XOR.
please check it out! Thank you!
Also can I add more programs in scripts folder or are we required to add only one?
Thank You!

Added script to find unique element in C++

---

Scripts/binarySearch.cpp

hey!
I have added a program to check the presence of an element by Binary Search in C++.

Added Program for Binary Search

---

Scripts/selectionsort.cpp

Added selection sort prog

---

About-Me/MK.md

[Challenge #2](https://github.com/MAHIMA01/hacktoberfest-1/blob/Mahima/About-Me/MK.md) completed - Added details as required in initials.md (MK.md) file under About-Me folder.

Updated About-Me Folder with MK.md file

---

Contributor.md

Just completed the first challenge!

Complete challenge #1

---

About-Me/pa.md

More one challenge completed!
- Add pa.md in About-Me

Complete challenge #2

---

Scripts/time-based_greetings.py

I tried to improve the hello world code by adding a greeting based on the current time.

Complete challenge #3

---

Contributor.md

My first time doing pull request, still need working to do! :)

JiriJAdam Hacktoberfest

---

Scripts/GCD.java

Added a simple java program to find the greatest common denominator between two numbers.

Added GCD.java

---

Application/index.js

Work finished!
It was a very nice experience to participate in this event. In Brazil we don't have Halloween but hunting for issues for beginners, sending the Pull Request and waiting to be approved, it felt like being on a Halloween (what I know from the movies), asking for trick or treat.
I hope my Pull Requests will be accepted by digitalocean.
Thank you very much for the experience!

Complete challenge #4

---

Contributor.md

Challenge 1

---

About-Me/va.md
Contributor.md
Scripts/random_print_of_helloworld.py

Contributing as part of hactoberfest. I like the decoration of this repository.

Contribution with a random printer of 'hello world'

---

About-Me/lr.md
Application/index.js
Contributor.md
Scripts/heythere.py

Leslie rodriguez

---

About-Me/or.md
Contributor.md

challlege 1 completed on to the next

Added Oscar Romero to Contributors.md

---

Contributor.md

- Name: (Kenneth Luster)
- Bio: Blockchain Dev Student!
- Link: [Github](https://github.com/KenMan79)

Kenneth Add Me Please

---

About-Me/Kl.md
Application/index.js
Contributor.md
Scripts/challlengeExample.js

Kenneth luster 

---

About-Me/lc.md
Application/index.js
Contributor.md
Scripts/heyWorld.js

Lc branch 

---

About-Me/ko.md

Hi, newby is here. Thank for accept my pull request

adding about Krichkorn

---

Scripts/Factorial.py

[Challenge #3](https://github.com/jinwoov/hacktoberfest#challenge-3) completed - Added a .py file [Factorial of a Number](https://github.com/MAHIMA01/hacktoberfest-1/blob/Mahima/Scripts/Factorial.py)

Created Factorial of a Number Program using Python
